# Generated by Django 6.1.1 on 2026-10-09 12:29

import core_settings.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='PharmaCare', max_length=150)),
                ('tagline', models.CharField(blank=True, default='Pharmacy Management System', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacy/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core_settings.models.validate_logo_size])),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('currency_code', models.CharField(choices=[('PKR', 'Pakistani Rupee (PKR)')], default='PKR', max_length=3)),
                ('default_tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('low_stock_threshold', models.PositiveIntegerField(default=20, help_text='Default threshold in individual stock units.')),
                ('expiry_alert_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(365)])),
                ('receipt_footer', models.CharField(blank=True, default='Thank you for shopping with us!', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pharmacy Profile',
                'verbose_name_plural': 'Pharmacy Profile',
            },
        ),
    ]
