
# reports/pdf_reports.py

from io import BytesIO
from datetime import date, datetime
from decimal import Decimal
from xml.sax.saxutils import escape

from django.utils import timezone

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    LongTable,
    TableStyle,
    KeepTogether,
)

from .services import (
    build_sales_report,
    build_purchase_report,
    build_inventory_report,
    build_profit_report,
    get_sales_queryset,
    get_purchase_queryset,
    get_inventory_report_queryset,
)


TEAL = colors.HexColor("#0F766E")
DARK = colors.HexColor("#163536")
LIGHT = colors.HexColor("#E8F5F2")
BORDER = colors.HexColor("#DCE7E5")
MUTED = colors.HexColor("#667784")
WHITE = colors.white

ZERO = Decimal("0.00")


def clean(value):
    """Convert untrusted database values into safe PDF text."""
    if value is None or value == "":
        return "—"

    return escape(str(value))


def amount(value):
    try:
        value = Decimal(str(value or 0))
    except (ValueError, TypeError, ArithmeticError):
        value = ZERO

    return f"Rs. {value:,.2f}"


def quantity(value):
    try:
        return f"{int(value or 0):,}"
    except (ValueError, TypeError):
        return "0"


def date_label(value):
    if not value:
        return "—"

    if isinstance(value, datetime):
        if timezone.is_aware(value):
            value = timezone.localtime(value)
        return value.strftime("%d %b %Y %I:%M %p")

    if isinstance(value, date):
        return value.strftime("%d %b %Y")

    return str(value)


def styles():
    return {
        "title": ParagraphStyle(
            "PdfTitle",
            fontName="Helvetica-Bold",
            fontSize=19,
            leading=24,
            textColor=DARK,
            spaceAfter=5,
        ),
        "subtitle": ParagraphStyle(
            "PdfSubtitle",
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=MUTED,
        ),
        "section": ParagraphStyle(
            "PdfSection",
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=DARK,
        ),
        "normal": ParagraphStyle(
            "PdfNormal",
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=DARK,
            wordWrap="CJK",
        ),
        "small": ParagraphStyle(
            "PdfSmall",
            fontName="Helvetica",
            fontSize=7,
            leading=10,
            textColor=DARK,
            wordWrap="CJK",
        ),
        "header": ParagraphStyle(
            "PdfTableHeader",
            fontName="Helvetica-Bold",
            fontSize=7,
            leading=10,
            textColor=WHITE,
            wordWrap="CJK",
        ),
        "metric": ParagraphStyle(
            "PdfMetric",
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=TEAL,
        ),
        "label": ParagraphStyle(
            "PdfMetricLabel",
            fontName="Helvetica",
            fontSize=7,
            leading=10,
            textColor=MUTED,
        ),
    }


def paragraph(value, style):
    return Paragraph(clean(value), style)


def pdf_footer(canvas, doc):
    canvas.saveState()

    width, _ = doc.pagesize

    canvas.setStrokeColor(BORDER)
    canvas.line(
        15 * mm,
        16 * mm,
        width - 15 * mm,
        16 * mm,
    )

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)

    canvas.drawString(
        15 * mm,
        11 * mm,
        "Generated by PharmaCare Pharmacy Management System",
    )

    canvas.drawRightString(
        width - 15 * mm,
        11 * mm,
        f"Page {doc.page}",
    )

    canvas.restoreState()


def build_summary_cards(summary, available_width, st):
    if not summary:
        return []

    cards = []

    for label, value in summary:
        cards.append([
            Paragraph(clean(label), st["label"]),
            Paragraph(clean(value), st["metric"]),
        ])

    # Two columns, with each cell containing a label and value.
    rows = []

    for index in range(0, len(cards), 2):
        left = cards[index]
        right = (
            cards[index + 1]
            if index + 1 < len(cards)
            else [
                Paragraph("", st["label"]),
                Paragraph("", st["metric"]),
            ]
        )

        left_content = [
            left[0],
            Spacer(1, 4),
            left[1],
        ]

        right_content = [
            right[0],
            Spacer(1, 4),
            right[1],
        ]

        rows.append([
            left_content,
            right_content,
        ])

    table = Table(
        rows,
        colWidths=[
            available_width / 2,
            available_width / 2,
        ],
        hAlign="LEFT",
    )

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT),
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))

    return [
        table,
        Spacer(1, 14),
    ]


def build_data_table(headers, rows, available_width, st):
    """
    LongTable repeats headings on new pages.

    All database-provided text is escaped before
    passing to ReportLab Paragraph.
    """

    column_count = len(headers)
    column_width = available_width / column_count

    header_row = [
        paragraph(header, st["header"])
        for header in headers
    ]

    table_data = [header_row]

    for row in rows:
        table_data.append([
            paragraph(value, st["small"])
            for value in row
        ])

    if len(table_data) == 1:
        table_data.append([
            paragraph(
                "No records found." if i == 0 else "",
                st["small"],
            )
            for i in range(column_count)
        ])

    table = LongTable(
        table_data,
        colWidths=[column_width] * column_count,
        repeatRows=1,
        hAlign="LEFT",
    )

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), TEAL),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [
            WHITE,
            colors.HexColor("#F5FAF9"),
        ]),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 9),
        ("TOPPADDING", (0, 0), (-1, 0), 9),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("TOPPADDING", (0, 1), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, -1), (-1, -1), 0.5, BORDER),
    ]))

    return table


def report_definition(report_type, filters):
    """
    Build summary and row data.

    Reuses existing report services and queryset
    security rules.
    """

    if report_type == "sales":
        report = build_sales_report(filters)
        totals = report["summary"]

        summary = [
            ("Sales Revenue", amount(totals.get("revenue"))),
            ("Collected", amount(totals.get("collected"))),
            ("Outstanding", amount(totals.get("outstanding"))),
            ("Completed Sales", quantity(totals.get("sale_count"))),
            ("Average Sale", amount(totals.get("average_sale"))),
            ("Discounts", amount(totals.get("discounts"))),
        ]

        headers = [
            "Invoice",
            "Date",
            "Customer",
            "Branch",
            "Total",
            "Collected",
            "Outstanding",
        ]

        queryset = (
            get_sales_queryset(filters)
            .order_by("completed_at", "pk")
            .values(
                "invoice_number",
                "completed_at",
                "customer_name",
                "branch__name",
                "total_amount",
                "paid_amount",
                "change_amount",
            )
        )

        def rows():
            for sale in queryset.iterator(chunk_size=500):
                total = Decimal(sale["total_amount"] or 0)
                paid = Decimal(sale["paid_amount"] or 0)
                change = Decimal(sale["change_amount"] or 0)

                collected = max(
                    ZERO,
                    min(total, paid - change),
                )

                yield [
                    sale["invoice_number"],
                    date_label(sale["completed_at"]),
                    sale["customer_name"] or "Walk-in",
                    sale["branch__name"],
                    amount(total),
                    amount(collected),
                    amount(max(ZERO, total - collected)),
                ]

        return {
            "title": "Sales Report",
            "summary": summary,
            "headers": headers,
            "rows": rows(),
            "note": (
                "Collections and outstanding amounts reflect "
                "current invoice balances, not cash received "
                "only during the selected report period."
            ),
        }

    if report_type == "purchases":
        report = build_purchase_report(filters)
        totals = report["summary"]

        summary = [
            ("Purchase Orders", quantity(totals.get("order_count"))),
            ("Ordered Value", amount(totals.get("ordered_value"))),
            ("Stock Receipts", quantity(totals.get("receipt_count"))),
            ("Received Cost", amount(totals.get("gross_received_cost"))),
            (
                "Received Packs",
                quantity(totals.get("total_received_packs")),
            ),
            ("Discounts", amount(totals.get("discounts"))),
        ]

        headers = [
            "Purchase #",
            "Date",
            "Supplier",
            "Branch",
            "Status",
            "Ordered Value",
        ]

        queryset = (
            get_purchase_queryset(filters)
            .order_by("purchase_date", "pk")
            .values(
                "purchase_number",
                "purchase_date",
                "supplier__name",
                "branch__name",
                "status",
                "total_amount",
            )
        )

        def rows():
            for purchase in queryset.iterator(chunk_size=500):
                yield [
                    purchase["purchase_number"],
                    date_label(purchase["purchase_date"]),
                    purchase["supplier__name"],
                    purchase["branch__name"],
                    purchase["status"],
                    amount(purchase["total_amount"]),
                ]

        return {
            "title": "Purchase Report",
            "summary": summary,
            "headers": headers,
            "rows": rows(),
            "note": (
                "Purchase order values and stock receipt "
                "costs represent different business events."
            ),
        }

    if report_type == "inventory":
        report = build_inventory_report(filters)
        totals = report["summary"]

        summary = [
            ("Total Batches", quantity(totals.get("batch_count"))),
            ("Stock Units", quantity(totals.get("units_in_stock"))),
            (
                "Estimated Cost Value",
                amount(totals.get("estimated_cost_value")),
            ),
            (
                "Estimated Retail Value",
                amount(totals.get("estimated_retail_value")),
            ),
            (
                "Expired Batches",
                quantity(totals.get("expired_batches")),
            ),
            (
                "Expiring in 30 Days",
                quantity(totals.get("expiring_30_days")),
            ),
        ]

        headers = [
            "Medicine",
            "Batch",
            "Branch",
            "Expiry",
            "Units",
            "Cost Value",
            "Retail Value",
        ]

        queryset = get_inventory_report_queryset(filters)

        def rows():
            for batch in queryset.iterator(chunk_size=500):
                pack_size = max(
                    int(batch.medicine.pack_size or 1),
                    1,
                )

                unit_count = Decimal(batch.quantity)

                cost_value = (
                    unit_count
                    * batch.purchase_price
                    / Decimal(pack_size)
                )

                retail_value = (
                    unit_count
                    * batch.selling_price
                    / Decimal(pack_size)
                )

                yield [
                    batch.medicine.name,
                    batch.batch_number,
                    batch.branch.name,
                    date_label(batch.expiry_date),
                    quantity(batch.quantity),
                    amount(cost_value),
                    amount(retail_value),
                ]

        return {
            "title": "Inventory Report",
            "summary": summary,
            "headers": headers,
            "rows": rows(),
            "note": (
                "Inventory is a current stock snapshot. "
                "Valuation is estimated using stored batch "
                "prices and includes all scoped batches."
            ),
        }

    if report_type == "profit":
        report = build_profit_report(filters)
        totals = report["summary"]

        summary = [
            (
                "Revenue Including Tax",
                amount(totals.get("revenue_including_tax")),
            ),
            (
                "Net Sales Excluding Tax",
                amount(totals.get("net_sales_excluding_tax")),
            ),
            (
                "Estimated COGS",
                amount(totals.get("estimated_cogs")),
            ),
            (
                "Estimated Gross Profit",
                amount(totals.get("estimated_gross_profit")),
            ),
            (
                "Estimated Margin",
                f"{totals.get('estimated_margin_percent', 0)}%",
            ),
            (
                "Completed Sales",
                quantity(totals.get("sale_count")),
            ),
        ]

        headers = [
            "Financial Metric",
            "Estimated Value",
        ]

        rows = [
            ["Revenue Including Tax", summary[0][1]],
            ["Net Sales Excluding Tax", summary[1][1]],
            ["Estimated Cost of Goods Sold", summary[2][1]],
            ["Estimated Gross Profit", summary[3][1]],
            ["Estimated Gross Margin", summary[4][1]],
        ]

        return {
            "title": "Estimated Profit Report",
            "summary": summary,
            "headers": headers,
            "rows": rows,
            "note": (
                "IMPORTANT: Profit values are estimates. "
                "SaleItem does not store immutable historical "
                "purchase cost snapshots. Current batch prices "
                "may differ from costs at the time of sale. "
                "This is not an audited profit statement."
            ),
        }

    raise ValueError("Unsupported report type")


def generate_report_pdf(
    *,
    report_type,
    filters,
    generated_by,
    branch_label,
):
    """
    Returns fully generated PDF bytes.

    Suitable for Django HttpResponse.
    """

    definition = report_definition(report_type, filters)

    output = BytesIO()

    page_size = (
        A4
        if report_type == "profit"
        else landscape(A4)
    )

    doc = SimpleDocTemplate(
        output,
        pagesize=page_size,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=17 * mm,
        bottomMargin=22 * mm,
        title=f"PharmaCare - {definition['title']}",
        author="PharmaCare Pharmacy Management System",
    )

    st = styles()
    available_width = doc.width

    story = []

    # --------------------------------------------------------
    # BRAND HEADER
    # --------------------------------------------------------

    brand = Table(
        [[
            Paragraph(
                "<b>PharmaCare</b>",
                ParagraphStyle(
                    "Brand",
                    fontName="Helvetica-Bold",
                    fontSize=21,
                    leading=26,
                    textColor=TEAL,
                ),
            ),
            Paragraph(
                clean(definition["title"]),
                ParagraphStyle(
                    "ReportTitleRight",
                    fontName="Helvetica-Bold",
                    fontSize=15,
                    leading=20,
                    alignment=TA_RIGHT,
                    textColor=DARK,
                ),
            ),
        ]],
        colWidths=[
            available_width * 0.5,
            available_width * 0.5,
        ],
    )

    brand.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("LINEBELOW", (0, 0), (-1, -1), 1.4, TEAL),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
    ]))

    story.append(brand)
    story.append(Spacer(1, 12))

    generated_at = timezone.localtime(
        timezone.now()
    ).strftime("%d %b %Y %I:%M %p")

    period = (
        f"{date_label(filters.date_from)} - "
        f"{date_label(filters.date_to)}"
    )

    if report_type == "inventory":
        period = "Current inventory snapshot"

    metadata = [
        ["Branch", branch_label],
        ["Report Period", period],
        ["Generated By", generated_by],
        ["Generated At", generated_at],
    ]

    metadata_rows = [
        [
            paragraph(label, st["small"]),
            paragraph(value, st["normal"]),
        ]
        for label, value in metadata
    ]

    metadata_table = Table(
        metadata_rows,
        colWidths=[
            34 * mm,
            available_width - 34 * mm,
        ],
        hAlign="LEFT",
    )

    metadata_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))

    story.append(metadata_table)
    story.append(Spacer(1, 13))

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    story.append(
        Paragraph("Report Summary", st["section"])
    )
    story.append(Spacer(1, 8))

    story.extend(
        build_summary_cards(
            definition["summary"],
            available_width,
            st,
        )
    )

    # --------------------------------------------------------
    # RECORDS
    # --------------------------------------------------------

    story.append(
        Paragraph("Detailed Records", st["section"])
    )
    story.append(Spacer(1, 8))

    story.append(
        build_data_table(
            definition["headers"],
            definition["rows"],
            available_width,
            st,
        )
    )

    story.append(Spacer(1, 14))
    story.append(
        Paragraph(
            clean(definition["note"]),
            st["normal"],
        )
    )

    doc.build(
        story,
        onFirstPage=pdf_footer,
        onLaterPages=pdf_footer,
    )

    return output.getvalue()
