# Generated by Django 6.1.1 on 2026-10-08 15:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockadjustment'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier_delivery_note', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchases.purchase')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('received_packs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pack_size', models.PositiveIntegerField(help_text='Snapshot of units per pack when stock was received.', validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Cost per full pack.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price per full pack.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_batch', models.ForeignKey(blank=True, editable=False, help_text='Inventory batch updated or created during receipt posting.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_items', to='inventory.inventorybatch')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='purchases.purchaseitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchases.purchasereceipt')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['purchase', 'received_at'], name='purchases_p_purchas_e7d12a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptitem',
            index=models.Index(fields=['purchase_item', 'batch_number'], name='purchases_p_purchas_4888df_idx'),
        ),
    ]
