# Generated by Django 6.1.1 on 2026-09-26 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('medicines', '0002_medicine_controlled_medicine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='branches.branch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='medicines.medicine')),
            ],
        ),
    ]
