# Generated by Django 6.1.1 on 2026-10-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0001_initial'),
        ('medicines', '0002_medicine_controlled_medicine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorybatch',
            options={'ordering': ['expiry_date', 'batch_number']},
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['medicine', 'branch'], name='inventory_i_medicin_4e9020_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['expiry_date'], name='inventory_i_expiry__e4a18c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['branch', 'expiry_date'], name='inventory_i_branch__ef73ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(fields=('medicine', 'branch', 'batch_number'), name='unique_medicine_branch_batch'),
        ),
    ]
