# Generated by Django 6.1.1 on 2026-10-06 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorybatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Purchase price per full pack.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text="Stock quantity in the medicine's smallest sellable unit."),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per full pack.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
