# Generated by Django 6.1.1 on 2026-10-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('customer_type', models.CharField(choices=[('regular', 'Regular'), ('wholesale', 'Wholesale')], default='regular', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
                'indexes': [models.Index(fields=['name'], name='customers_c_name_f018e2_idx'), models.Index(fields=['customer_type', 'is_active'], name='customers_c_custome_5cafca_idx')],
            },
        ),
    ]
