# Generated by Django 6.1.1 on 2026-09-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine Category',
                'verbose_name_plural': 'Medicine Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], default='tablet', max_length=20)),
                ('strength', models.CharField(blank=True, help_text='Example: 500mg, 10mg/5ml', max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prescription_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicines.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='medicines_m_name_61a774_idx'), models.Index(fields=['generic_name'], name='medicines_m_generic_1e9386_idx'), models.Index(fields=['barcode'], name='medicines_m_barcode_ac4d36_idx'), models.Index(fields=['sku'], name='medicines_m_sku_5bae82_idx')],
            },
        ),
    ]
