# Generated by Django 6.1.1 on 2026-10-06 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_controlled_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='allow_loose_sale',
            field=models.BooleanField(default=False, help_text='Allow this medicine to be sold in individual units instead of full packs only.'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pack_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of smallest units in one full pack.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('bottle', 'Bottle'), ('tube', 'Tube'), ('pack', 'Pack'), ('box', 'Box'), ('vial', 'Vial'), ('ampoule', 'Ampoule'), ('piece', 'Piece')], default='tablet', help_text='Smallest sellable unit of this medicine.', max_length=20),
        ),
    ]
