# Generated by Django 6.1.1 on 2026-10-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_medicine_allow_loose_sale_alter_medicine_pack_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='use_pharmacy_default_tax',
            field=models.BooleanField(default=False, help_text='When enabled, use the current pharmacy default tax rate for new sales instead of medicine tax_rate.'),
        ),
    ]
