# Generated by Django 6.1.1 on 2026-10-06 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorybatch_purchase_price_and_more'),
        ('medicines', '0003_medicine_allow_loose_sale_alter_medicine_pack_size_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='unique_batch_per_sale',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='pack_size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_type',
            field=models.CharField(choices=[('pack', 'Pack'), ('unit', 'Loose Unit')], default='pack', max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_label',
            field=models.CharField(default='Unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'sale_type'], name='sales_salei_sale_id_c6fdd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gt', 0)), name='sale_item_stock_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('pack_size__gt', 0)), name='sale_item_pack_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(fields=('sale', 'inventory_batch', 'sale_type'), name='unique_batch_sale_type_per_sale'),
        ),
    ]
