# Generated by Django 6.1.1 on 2026-10-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0002_remove_saleitem_unique_batch_per_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional registered customer. Null means a walk-in or unlinked sale.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer'),
        ),
    ]
